env:
  global:
    - CODECOV_TOKEN="c1f84c90-5c04-442e-8f07-2f477aa95052" # https://codecov.io

language: node_js

node_js:
  - 10

before_script:
  - npm install -g codecov

script:
  - npm run coverage # get the coverage run before building
  - codecov          # upload coverage reports to codecov.io
  - npm run build    # we have a build badge, so run the build
